version: "3.9"

networks:
  default:
    name: workspace
    driver: bridge

services:

  db:
    networks:
      - default
    image: postgres:15-alpine
    hostname: postgres
    container_name: db
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: forge
    ports:
      - "5432:5432"

  saas:
    init: true
    tty: true
    networks:
      - default
    build:
      context: .
      dockerfile: forge/saas/Dockerfile
      target: dev
      args:
        NODE_ENV: development
        PORT: 3000
    env_file:
      - forge/saas/.env.local
    image: forge-saas:development
    container_name: forge-saas-development
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - NODE_ENV=development
      - DATABASE_URL=postgres://user:password@db:5432/postgres
    volumes:
      - ./forge/saas:/app/forge/saas
      - /app/forge/node_modules
      - /app/node_modules
    depends_on:
      - db

volumes:
  db:
